weapp:
  restart: always
  build: ./src
  command: node index.js
  ports:
    - "80:80"
  volumes:
    - ./src:/src
  environment:
    - EGG_SERVER_ENV=prod
    - NODE_ENV=production
    - PORT=80
  links:
    - redis
    - mysql
redis:
  restart: always
  image: redis 
  ports:
    - "6379"
  volumes:
    - ./db/redis:/src
  links:
    - mysql
mysql:
  restart: always
  image: mysql
  ports:
    - "3306"
  volumes:
    - ./db/mysql:/docker-entrypoint-initdb.d
    - ./db/mysqlData:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=winfan123
