weapp:
  restart: always
  build: ./src
  command: node index.js
  ports:
    - "7001:7001"
  volumes:
    - ./src:/src
  environment:
    - EGG_SERVER_ENV=docker
    - PORT=7001
  links:
    - redis
    - mysql
redis:
  restart: always
  image: redis 
  ports:
    - "6379:6379"
  volumes:
    - ./db/redis:/src
  links:
    - mysql
mysql:
  restart: always
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - ./db/mysql:/docker-entrypoint-initdb.d
    - ./db/mysqlData:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=winfan123
